#!/bin/bash
echo "🚀 Simple Deployment"
echo ""
echo "1. Zip your project:"
echo "   zip -r project.zip . -x '*.pyc' '*/__pycache__/*'"
echo ""
echo "2. Upload to:"
echo "   - Netlify (frontend/ folder)"
echo "   - PythonAnywhere (backend/ folder)"
echo "   - Vercel (whole project)"
echo ""
echo "3. Or use GitHub -> Deploy button"
echo ""
echo "Remember: Deployed > Perfect"
