#!/bin/bash
echo "🚀 STARTING SPECIALIZED AGENT SWARM..."
echo ""
echo "Open new Termux sessions for each agent:"
echo ""
echo "Session 1: python agent_psychology.py"
echo "Session 2: python agent_legal.py"
echo "Session 3: python agent_security.py"
echo "Session 4: python agent_tech_guru.py"
echo "Session 5: python agent_marketing.py"
echo "Session 6: python agent_reviewer.py"
echo "Session 7: python agent_coder.py"
echo ""
echo "Then send tasks: python send_to_all.py 'Your epic request here'"
echo ""
echo "🧠 Your swarm of psychological, legal, security, and tech experts is ready!"
